import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { sampleData } from './data/sample';
import { exportMaster, exportResults, importMaster, downloadCsv, type MasterKind } from './services/csv';
import { selectParts } from './services/selector';
import { DB_NAME, DB_VERSION, loadMaster, saveMaster } from './services/storage';
import { authorizeGoogleDrive, disconnectGoogleDrive, DRIVE_APP_FOLDER, DRIVE_PARENT_FOLDER, getGoogleDriveBackupInfo, GOOGLE_CLIENT_ID_KEY, isGoogleDriveAuthorized, loadMasterFromGoogleDrive, saveMasterToGoogleDrive } from './services/googleDrive';
import type { AppSyncData, MasterData, Selection, UnitResult } from './types';

const statusLabel = { selected: '選定済み', multiple: '複数候補あり', none: '候補なし' } as const;
const optionLabel = (specifications: MasterData['specifications'], optionCode: string) => specifications.flatMap((specification) => specification.options).find((option) => option.code === optionCode)?.label ?? optionCode;
const masterCountSummary = (master: MasterData) => `仕様 ${master.specifications.length}件／ユニット ${master.units.length}件／PL条件 ${master.rules.length}件`;
const masterKindLabel = { specifications:'仕様項目マスター', units:'ユニットマスター', rules:'PL選定条件マスター' } as const;
function ConditionChip({ sequence, code, values, specifications, selectedValue }:{ sequence:number; code:string; values:string[]; specifications:MasterData['specifications']; selectedValue?:string }) {
  const [tooltip, setTooltip] = useState<{left:number;top:number}>();
  const specification = specifications.find((item) => item.code === code);
  const allowedOptions = values.map((value) => ({code:value,label:optionLabel(specifications,value)}));
  const allowed = allowedOptions.map((option) => `${option.code} ${option.label}`).join(' / ');
  const selectedLabel = selectedValue ? optionLabel(specifications,selectedValue) : '';
  const selected = selectedValue ? `${selectedValue} ${selectedLabel}` : '未選択';
  const status = !selectedValue ? 'pending' : values.includes(selectedValue) ? 'matched' : 'mismatched';
  const statusText = status==='matched' ? '✓ 現在の選択と一致' : status==='mismatched' ? '× 現在の選択と不一致' : '! 仕様が未選択';
  const showTooltip = (element: HTMLElement) => { const rect=element.getBoundingClientRect(); setTooltip({left:Math.max(12,Math.min(rect.left,window.innerWidth-472)),top:rect.bottom+150<window.innerHeight?rect.bottom+10:Math.max(12,rect.top-140)}); };
  return <span className={`condition-chip ${status}`} tabIndex={0} aria-label={`${code} ${specification?.name??''}、適合条件 ${allowed}、現在の選択 ${selected}`} onMouseEnter={(event)=>showTooltip(event.currentTarget)} onMouseLeave={()=>setTooltip(undefined)} onFocus={(event)=>showTooltip(event.currentTarget)} onBlur={()=>setTooltip(undefined)}>
    <small><span className="condition-sequence">{sequence}.</span><b>{code}</b><span>{specification?.name??''}</span></small><span className="condition-values">{allowedOptions.map((option)=><span className={`condition-value ${option.code===selectedValue?'selected-value':''}`} key={option.code}><b>{option.code}</b><span>{option.label}</span>{option.code===selectedValue&&<i>選択中</i>}</span>)}</span><span className="condition-result">{status==='matched'?'✓ 一致':status==='mismatched'?'× 不一致':'! 未選択'}</span>
    {tooltip&&createPortal(<span className={`condition-tooltip ${status}`} role="tooltip" style={{left:tooltip.left,top:tooltip.top}}><span className="tooltip-heading"><strong>{sequence}. {code}　{specification?.name??'仕様名未登録'}</strong><b className="tooltip-status">{statusText}</b></span><span className="tooltip-section"><b>適合条件</b><span className="tooltip-values">{allowedOptions.map((option)=><span className={`tooltip-value ${option.code===selectedValue?'selected-value':''}`} key={option.code}><code>{option.code}</code><span>{option.label}</span>{option.code===selectedValue&&<i>選択中</i>}</span>)}</span></span>{status==='mismatched'&&selectedValue&&<span className="tooltip-current-mismatch"><b>現在の選択</b><span className="tooltip-value"><code>{selectedValue}</code><span>{selectedLabel}</span></span></span>}</span>,document.body)}
  </span>;
}
function App() {
  const [data, setData] = useState<MasterData>(sampleData); const [selection, setSelection] = useState<Selection>({});
  const [results, setResults] = useState<UnitResult[] | null>(null); const [active, setActive] = useState<UnitResult>();
  const [search, setSearch] = useState(''); const [tab, setTab] = useState<'select'|'master'>('select');
  const [workTab, setWorkTab] = useState<'specifications'|'results'>('specifications'); const [notice, setNotice] = useState('');
  const [driveClientId, setDriveClientId] = useState(() => localStorage.getItem(GOOGLE_CLIENT_ID_KEY) ?? '');
  const [driveConnected, setDriveConnected] = useState(false); const [driveBusy, setDriveBusy] = useState(false);
  const [autoSync, setAutoSync] = useState(false); const [syncStatus, setSyncStatus] = useState('自動同期オフ');
  const [returnRuleUnit, setReturnRuleUnit] = useState('');
  const importRef = useRef<HTMLInputElement>(null); const [importKind, setImportKind] = useState<MasterKind>('specifications');
  useEffect(() => { loadMaster().then(async(saved) => { if (!saved) { await saveMaster(sampleData); return; } const seededUnits=['110','120','131','130','200','210','220','230','300','310','320','350','360'].filter((unitNo)=>!saved.rules.some((rule)=>rule.unitNo===unitNo)); if(seededUnits.length===0){setData(saved);return} const addedRules=sampleData.rules.filter((rule)=>seededUnits.includes(rule.unitNo));const migrated={...saved,rules:[...saved.rules,...addedRules]};setData(migrated);await saveMaster(migrated);setNotice(`${seededUnits.join('、')}のPL条件${addedRules.length}件を既存マスターへ追加しました。`); }).catch(() => setNotice('IndexedDBを利用できないため、サンプルデータで起動しました。')); }, []);
  useEffect(() => { const saved=localStorage.getItem('parts-list-selector-selection'); if(saved) { try { setSelection(JSON.parse(saved) as Selection); } catch { localStorage.removeItem('parts-list-selector-selection'); } } }, []);
  useEffect(() => { localStorage.setItem('parts-list-selector-selection',JSON.stringify(selection)); }, [selection]);
  useEffect(() => { if(!driveConnected||!autoSync) return; setSyncStatus('変更を検出しました'); const timer=window.setTimeout(async()=>{setSyncStatus('同期中…');try{await saveMasterToGoogleDrive({schemaVersion:1,masterData:data,selection,syncedAt:new Date().toISOString()});setSyncStatus(`同期済み ${new Date().toLocaleTimeString('ja-JP')}`)}catch(error){setAutoSync(false);setSyncStatus('同期エラー');setNotice(error instanceof Error?error.message:'自動同期に失敗しました。')}},1200);return()=>window.clearTimeout(timer)},[data,selection,driveConnected,autoSync]);
  const specs = useMemo(() => [...data.specifications].sort((a,b) => a.order-b.order), [data]);
  const filtered = (results ?? []).filter((r) => `${r.unit.name} ${r.unit.note} ${r.candidates.map(c=>c.partNumber).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
  const updateData = async (next: MasterData) => { setData(next); await saveMaster(next); setNotice('マスターデータを保存しました。'); };
  const runSelection = () => { setResults(selectParts(data, selection)); setActive(undefined); setWorkTab('results'); };
  const openResults = () => { setResults(selectParts(data, selection)); setActive(undefined); setWorkTab('results'); };
  const returnToRuleMaster = () => { setTab('master'); setTimeout(()=>document.getElementById('pl-rule-master')?.scrollIntoView({behavior:'smooth',block:'center'})); };
  const jumpToSpecification = (code: string, unitNo: string) => { setReturnRuleUnit(unitNo); setTab('select'); setWorkTab('specifications'); setTimeout(() => { const row=document.getElementById(`spec-${code}`); row?.scrollIntoView({behavior:'smooth',block:'center'}); row?.querySelector('select')?.focus(); row?.classList.add('jump-target'); setTimeout(()=>row?.classList.remove('jump-target'),1800); }); };
  const confirmSelection = (unitNo:string, partNumber:string) => setResults((old) => old?.map((r) => r.unit.no===unitNo ? {...r,confirmedPartNumber:partNumber}:r) ?? null);
  const connectDrive = async () => { setDriveBusy(true); try { await authorizeGoogleDrive(driveClientId); localStorage.setItem(GOOGLE_CLIENT_ID_KEY, driveClientId.trim()); setDriveConnected(isGoogleDriveAuthorized()); setNotice('Google Driveに接続しました。'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Google Driveへの接続に失敗しました。'); } finally { setDriveBusy(false); } };
  const createSyncData = ():AppSyncData => ({schemaVersion:1,masterData:data,selection,syncedAt:new Date().toISOString()});
  const saveToDrive = async () => { setDriveBusy(true); try { const existing=await getGoogleDriveBackupInfo(); const warning=existing ? `【上書き警告】\nブラウザ → Google Drive の方向で保存します。\n\nブラウザ（保存する側）: ${masterCountSummary(data)}／仕様選択 ${Object.values(selection).filter(Boolean).length}件\nGoogle Drive（上書きされる側）: ${masterCountSummary(existing.data.masterData)}／仕様選択 ${Object.values(existing.data.selection).filter(Boolean).length}件\nDrive最終更新: ${existing.modifiedTime?new Date(existing.modifiedTime).toLocaleString('ja-JP'):'不明'}\n\nGoogle Driveのデータは元に戻せません。内容と更新日時を確認して「OK」を押してください。` : `Google Driveに新規バックアップを作成します。\n保存内容: ${masterCountSummary(data)}／仕様選択 ${Object.values(selection).filter(Boolean).length}件\n\n続行しますか？`; if (!window.confirm(warning)) return; const modified = await saveMasterToGoogleDrive(createSyncData()); setNotice(`Google Driveの「${DRIVE_PARENT_FOLDER}/${DRIVE_APP_FOLDER}」へ保存しました（${new Date(modified).toLocaleString('ja-JP')}）。`); } catch (error) { setDriveConnected(isGoogleDriveAuthorized()); setNotice(error instanceof Error ? error.message : 'Google Driveへの保存に失敗しました。'); } finally { setDriveBusy(false); } };
  const loadFromDrive = async () => { setDriveBusy(true); try { const backup = await loadMasterFromGoogleDrive(); const remote=backup.data.masterData; if (!Array.isArray(remote.specifications)||!Array.isArray(remote.units)||!Array.isArray(remote.rules)||remote.specifications.some((specification)=>!/^S\d{3}$/.test(specification.code)||!Array.isArray(specification.options)||typeof specification.reference!=='string'||typeof specification.note!=='string')||remote.rules.some((rule)=>'name' in rule||typeof rule.note!=='string'||typeof rule.selectable!=='boolean'||Object.values(rule.conditions).some((values)=>!Array.isArray(values)))) throw new Error('Google DriveのファイルはユニークPL・複数許容条件方式ではありません。'); const warning=`【上書き警告】\nGoogle Drive → ブラウザ の方向で読み込みます。\n\nGoogle Drive（読み込む側）: ${masterCountSummary(remote)}／仕様選択 ${Object.values(backup.data.selection).filter(Boolean).length}件\nDrive最終更新: ${backup.modifiedTime?new Date(backup.modifiedTime).toLocaleString('ja-JP'):'不明'}\nブラウザ（上書きされる側）: ${masterCountSummary(data)}／仕様選択 ${Object.values(selection).filter(Boolean).length}件\n\n現在のブラウザ内データは元に戻せません。内容と更新日時を確認して「OK」を押してください。`; if (!window.confirm(warning)) return; setAutoSync(false); await updateData(remote);setSelection(backup.data.selection);setResults(null); setNotice('Google Driveからマスターと仕様選択状態を読み込みました。'); } catch (error) { setDriveConnected(isGoogleDriveAuthorized()); setNotice(error instanceof Error ? error.message : 'Google Driveからの読み込みに失敗しました。'); } finally { setDriveBusy(false); } };
  const onImport = async (file?:File) => { if (!file) return; try { const imported=importMaster(await file.text(),importKind); const currentCount=data[importKind].length; if (!window.confirm(`【CSV上書き警告】\n「${file.name}」を取り込むと、${masterKindLabel[importKind]}の登録内容を全件置き換えます。\n\n現在（上書きされる側）: ${currentCount}件\nCSV（取り込む側）: ${imported.length}件\n\nこの操作は元に戻せません。続行しますか？`)) return; await updateData({...data,[importKind]:imported}); } catch(e) { setNotice(`取込エラー: ${e instanceof Error ? e.message:'形式を確認してください。'}`); } };
  return <div className="app">
    <header><div className="brand"><span className="logo">PL</span><div><h1>Parts List Selector</h1><p>仕様に適合する部品表を、ユニットごとに選定します</p></div></div><nav><button className={tab==='select'?'active':''} onClick={()=>setTab('select')}>仕様選択・結果</button><button className={tab==='master'?'active':''} onClick={()=>setTab('master')}>マスターデータ管理</button></nav></header>
    <main>{notice && <div className="notice" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
    {tab==='select' ? <section className="workspace">
      <div className="work-tabs" role="tablist" aria-label="PL選定作業">
        <button role="tab" aria-selected={workTab==='specifications'} className={workTab==='specifications'?'active':''} onClick={()=>setWorkTab('specifications')}><span>1</span> 仕様選択 <small>{Object.values(selection).filter(Boolean).length}/{specs.length}</small></button>
        <button role="tab" aria-selected={workTab==='results'} className={workTab==='results'?'active':''} onClick={openResults}><span>2</span> PL選定結果 <small>{results?.length??data.units.length}ユニット</small></button>
      </div>
      {workTab==='specifications' && returnRuleUnit && <div className="jump-return-bar"><span><b>{returnRuleUnit}</b> {data.units.find((unit)=>unit.no===returnRuleUnit)?.name} のPL条件を確認中</span><button onClick={returnToRuleMaster}>← PL選定条件マスターへ戻る</button></div>}
      {workTab==='specifications' ? <section className="panel tab-panel"><div className="section-heading"><div><span className="eyebrow">SPECIFICATIONS</span><h2>仕様選択</h2><p>各項目を選択してください。未選択の項目は空欄のまま選定できます。</p></div><span className="counter">{Object.values(selection).filter(Boolean).length} / {specs.length} 項目選択</span></div>
        <div className="spec-scroll"><div className="spec-column-head"><span>コード</span><span>仕様</span><span>選択項目</span><span>備考</span></div><div className="spec-grid">{specs.map((spec)=><label className="spec-row" id={`spec-${spec.code}`} key={spec.code}><span className="number">{spec.code}</span><span className="spec-info"><b>{spec.name}</b><small>No.{String(spec.no).padStart(2,'0')}{spec.reference&&`　参照: ${spec.reference}`}</small></span><select value={selection[spec.code]??''} onChange={(e)=>setSelection({...selection,[spec.code]:e.target.value})}><option value="">未選択</option>{spec.options.map((option)=><option key={option.code} value={option.code}>{option.code}　{option.label}</option>)}</select><span className={`spec-note ${spec.note?'':'empty'}`}>{spec.note||'—'}</span></label>)}</div></div>
        <div className="actions sticky-actions"><button className="secondary" onClick={()=>{setSelection({});setResults(null)}}>選択をクリア</button><button className="primary" onClick={runSelection}>PLを選定 <span>→</span></button></div>
      </section> : results ? <section className="panel tab-panel results" id="results"><div className="section-heading"><div><span className="eyebrow">SELECTION RESULTS</span><h2>PL選定結果</h2><div className="legend"><i className="dot green"/>選定済み <i className="dot amber"/>複数候補 <i className="dot red"/>候補なし</div></div><div className="result-actions"><button className="secondary" onClick={()=>setWorkTab('specifications')}>← 仕様を変更</button><button className="secondary" onClick={()=>downloadCsv('PL選定結果.csv',exportResults(results))}>CSV出力</button></div></div>
        <div className="toolbar"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ユニット名・PL品番・備考を検索"/><b>{filtered.length} ユニット</b></div>
        <div className="table-wrap"><table><thead><tr><th>No.</th><th>ユニット名</th><th>選定されたPL品番</th><th>判定状態</th><th>備考</th></tr></thead><tbody>{filtered.map(r=><tr key={r.unit.no} className={r.status} onClick={()=>setActive(r)}><td>{r.unit.no}</td><td><button className="link">{r.unit.name}</button></td><td>{r.confirmedPartNumber ?? (r.status==='selected'?r.candidates[0].partNumber:r.status==='multiple'?r.candidates.map(c=>c.partNumber).join(' / '):'—')}</td><td><span className={`badge ${r.status}`}>{r.status==='selected'?'✓':'⚠'} {statusLabel[r.status]}</span>{r.missingSpecificationCodes.length>0&&<small className="missing">不足: {r.missingSpecificationCodes.map(code=>`${code} ${specs.find(s=>s.code===code)?.name??''}`).join('、')}</small>}</td><td>{r.unit.note}</td></tr>)}</tbody></table></div>
      </section> : null}
    </section> : <MasterPanel data={data} selection={selection} initialRuleUnit={returnRuleUnit} onJumpToSpecification={jumpToSpecification} driveClientId={driveClientId} driveConnected={driveConnected} driveBusy={driveBusy} autoSync={autoSync} syncStatus={syncStatus} onAutoSyncChange={(enabled)=>{if(enabled&&!window.confirm(`自動同期を有効にすると、マスター3種類と仕様選択状態の変更をGoogle Driveへ自動保存します。\n\n現在: ${masterCountSummary(data)}／仕様選択 ${Object.values(selection).filter(Boolean).length}件\n\n初回同期でDrive側を上書きします。続行しますか？`))return;setAutoSync(enabled);setSyncStatus(enabled?'同期を開始します…':'自動同期オフ')}} onDriveClientIdChange={setDriveClientId} onDriveConnect={connectDrive} onDriveSave={saveToDrive} onDriveLoad={loadFromDrive} onDriveDisconnect={()=>{disconnectGoogleDrive();setDriveConnected(false);setAutoSync(false);setSyncStatus('自動同期オフ');setNotice('Google Driveとの接続を解除しました。')}} onReset={()=>{if(window.confirm(`【全マスター上書き警告】\n現在: ${masterCountSummary(data)}\nサンプル: ${masterCountSummary(sampleData)}\n\n現在の登録内容をサンプルで全件置き換えます。この操作は元に戻せません。続行しますか？`)) updateData(sampleData)}} onExport={(k)=>downloadCsv(`${k}.csv`,exportMaster(data,k))} onImport={(k)=>{setImportKind(k);setTimeout(()=>importRef.current?.click())}} />}</main>
    <input hidden ref={importRef} type="file" accept=".csv,text/csv" onChange={e=>{onImport(e.target.files?.[0]);e.target.value=''}} />
    {active && <Detail result={active} specs={data.specifications} onClose={()=>setActive(undefined)} onConfirm={confirmSelection}/>}<footer>ローカル保存: IndexedDB「{DB_NAME}」v{DB_VERSION}　｜　データはこのブラウザ内に保存されます</footer>
  </div>;
}

function MasterPanel({data,selection,initialRuleUnit,onJumpToSpecification,driveClientId,driveConnected,driveBusy,autoSync,syncStatus,onAutoSyncChange,onDriveClientIdChange,onDriveConnect,onDriveSave,onDriveLoad,onDriveDisconnect,onReset,onExport,onImport }:{data:MasterData;selection:Selection;initialRuleUnit:string;onJumpToSpecification:(code:string,unitNo:string)=>void;driveClientId:string;driveConnected:boolean;driveBusy:boolean;autoSync:boolean;syncStatus:string;onAutoSyncChange:(enabled:boolean)=>void;onDriveClientIdChange:(value:string)=>void;onDriveConnect:()=>void;onDriveSave:()=>void;onDriveLoad:()=>void;onDriveDisconnect:()=>void;onReset:()=>void;onExport:(k:MasterKind)=>void;onImport:(k:MasterKind)=>void}) {
  const [selectedMaster, setSelectedMaster] = useState<MasterKind>(initialRuleUnit?'rules':'specifications');
  const [masterSearch, setMasterSearch] = useState('');
  const ruleUnits = [...data.units].sort((a,b) => a.order-b.order);
  const [selectedRuleUnit, setSelectedRuleUnit] = useState(() => initialRuleUnit||ruleUnits[0]?.no||'');
  const blocks: { key: MasterKind; title: string; description: string; count: number }[] = [
    { key: 'specifications', title: '仕様項目マスター', description: '仕様コード・項目名・選択肢コード・参照・備考', count: data.specifications.length },
    { key: 'units', title: 'ユニットマスター', description: 'ユニットNo.・名称・表示順・備考', count: data.units.length },
    { key: 'rules', title: 'PL選定条件マスター', description: 'PL品番・備考・仕様コードごとの適合条件', count: data.rules.length },
  ];
  const query = masterSearch.trim().toLowerCase();
  const specifications = data.specifications.filter((item) => `${item.no} ${item.code} ${item.name} ${item.options.map((option)=>`${option.code} ${option.label}`).join(' ')} ${item.reference} ${item.note}`.toLowerCase().includes(query));
  const units = data.units.filter((item) => `${item.no} ${item.name} ${item.note}`.toLowerCase().includes(query));
  const rules = data.rules.filter((item) => item.unitNo === selectedRuleUnit && `${item.unitNo} ${item.partNumber} ${item.note} ${Object.values(item.conditions).flat().join(' ')}`.toLowerCase().includes(query));
  const specificationOrder = new Map(data.specifications.map((specification) => [specification.code,specification.order]));
  const monitoredCodes = [...new Set(data.rules.filter((rule) => rule.unitNo === selectedRuleUnit).flatMap((rule) => Object.keys(rule.conditions)))].sort((a,b)=>(specificationOrder.get(a)??Number.MAX_SAFE_INTEGER)-(specificationOrder.get(b)??Number.MAX_SAFE_INTEGER));
  const monitoredCodeNumbers = new Map(monitoredCodes.map((code,index) => [code,index+1]));
  const unselectedMonitoredCount = monitoredCodes.filter((code) => !selection[code]).length;
  const orderedConditions = (rule: MasterData['rules'][number]) => Object.entries(rule.conditions).sort(([codeA],[codeB]) => (monitoredCodeNumbers.get(codeA)??Number.MAX_SAFE_INTEGER)-(monitoredCodeNumbers.get(codeB)??Number.MAX_SAFE_INTEGER) || codeA.localeCompare(codeB));
  const isRuleMatch = (rule: MasterData['rules'][number]) => rule.selectable && Object.entries(rule.conditions).every(([code, allowed]) => Boolean(selection[code]) && allowed.includes(selection[code]));
  const selected = blocks.find((block) => block.key === selectedMaster)!;
  return <section className="panel master-panel">
    <div className="section-heading"><div><span className="eyebrow">MASTER DATA</span><h2>マスターデータ管理</h2><p>登録内容を確認し、CSVで一括更新できます。</p></div><button className="danger-outline" onClick={onReset}>サンプルに戻す</button></div>
    <div className="master-grid">{blocks.map((block)=><article className={selectedMaster===block.key?'active':''} key={block.key} onClick={()=>setSelectedMaster(block.key)}>
      <span className="file-icon">▤</span><h3>{block.title}</h3><p>{block.description}</p><strong>{block.count}<small> 件登録</small></strong>
      <div><button className="secondary" onClick={(event)=>{event.stopPropagation();onImport(block.key)}}>CSV取込</button><button className="secondary" onClick={(event)=>{event.stopPropagation();onExport(block.key)}}>CSV出力</button><button className="view-master" onClick={()=>setSelectedMaster(block.key)}>内容を表示 →</button></div>
    </article>)}</div>
    <section className="master-content" id="pl-rule-master" aria-live="polite">
      <div className="master-content-heading"><div><span className="eyebrow">REGISTERED DATA</span><h3>{selected.title}の登録内容</h3><p>{selectedMaster==='rules'?`${rules.length}件のユニークPLを表示`:`${selected.count}件中 ${selectedMaster==='specifications'?specifications.length:units.length}件を表示`}</p></div><label className="master-search"><span>⌕</span><input value={masterSearch} onChange={(event)=>setMasterSearch(event.target.value)} placeholder="表示中のマスターを検索" /></label></div>
      {selectedMaster==='rules' && <><div className="unit-rule-selector"><label htmlFor="rule-unit-select">ユニット</label><select id="rule-unit-select" value={selectedRuleUnit} onChange={(event)=>setSelectedRuleUnit(event.target.value)}>{ruleUnits.map((unit)=><option value={unit.no} key={unit.no}>{unit.no}　{unit.name}（{data.rules.filter((rule)=>rule.unitNo===unit.no).length}件）</option>)}</select><span>{rules.length}件のユニークPL</span></div><div className="selection-monitor"><div className="monitor-summary"><strong>このユニットに関係する仕様</strong><span className={unselectedMonitoredCount===0?'complete':''}>未選択仕様 {unselectedMonitoredCount}件</span></div>{monitoredCodes.length===0&&<em>このユニットのPL条件は未登録です</em>}{monitoredCodes.map((code,index)=>{const specification=data.specifications.find((item)=>item.code===code);const value=selection[code];return <button type="button" title={`${index+1}. ${code} ${specification?.name}の選択欄へ移動`} className={value?'selected':'unselected'} onClick={()=>onJumpToSpecification(code,selectedRuleUnit)} key={code}><small><span className="monitor-sequence">{index+1}.</span><b>{code}</b><span>{specification?.name}</span></small><b>{value?`${value} ${optionLabel(data.specifications,value)}`:'未選択'}</b><i>選択欄へ →</i></button>})}</div></>}
      <div className="master-table-wrap">
        {selectedMaster==='specifications' && <table><thead><tr><th>仕様コード</th><th>仕様No.</th><th>仕様項目名</th><th>選択肢コード・表示名</th><th>参照</th><th>備考</th></tr></thead><tbody>{specifications.map((item)=><tr key={item.code}><td><code>{item.code}</code></td><td>{item.no}</td><td><b>{item.name}</b></td><td><div className="option-list">{item.options.map((option)=><span key={option.code}><b>{option.code}</b> {option.label}</span>)}</div></td><td>{item.reference||'—'}</td><td>{item.note||'—'}</td></tr>)}</tbody></table>}
        {selectedMaster==='units' && <table><thead><tr><th>表示順</th><th>ユニットNo.</th><th>ユニット名</th><th>備考</th></tr></thead><tbody>{units.map((item)=><tr key={item.no}><td>{item.order}</td><td><code>{item.no}</code></td><td><b>{item.name}</b></td><td>{item.note||'—'}</td></tr>)}</tbody></table>}
        {selectedMaster==='rules' && <table><thead><tr><th>状態</th><th>PL品番</th><th>備考</th><th>適合条件（仕様コード）</th></tr></thead><tbody>{rules.map((item)=><tr className={`${isRuleMatch(item)?'rule-match':''} ${item.selectable?'':'rule-disabled'}`} key={item.id}><td>{isRuleMatch(item)?<span className="match-mark">✓ 該当</span>:item.selectable?'—':'選定対象外'}</td><td><b>{item.partNumber}</b></td><td>{item.note||'—'}</td><td><div className="condition-list">{orderedConditions(item).map(([code,values])=><ConditionChip sequence={monitoredCodeNumbers.get(code)??0} code={code} values={values} specifications={data.specifications} selectedValue={selection[code]} key={code}/>)}</div></td></tr>)}</tbody></table>}
        {(selectedMaster==='specifications'?specifications.length:selectedMaster==='units'?units.length:rules.length)===0 && <div className="empty-master">該当するデータがありません。</div>}
      </div>
    </section>
    <section className="drive-panel"><div className="drive-heading"><div className="drive-icon">G</div><div><span className="eyebrow">CLOUD BACKUP</span><h3>Google Drive保存・自動同期</h3><p>マスター3種類と仕様選択状態を「{DRIVE_PARENT_FOLDER}/{DRIVE_APP_FOLDER}」へ保存・復元します。</p></div><span className={`drive-status ${driveConnected?'connected':''}`}>{driveConnected?'● 接続済み':'○ 未接続'}</span></div>
      <div className="overwrite-warning" role="note"><b>⚠ 上書き方向と件数を確認してください</b><span><strong>保存</strong> ブラウザ → Google Drive　／　<strong>読込</strong> Google Drive → ブラウザ</span><span>現在のブラウザ内データ：{masterCountSummary(data)}</span></div>
      {!driveConnected ? <div className="drive-connect"><label><span>Google OAuth クライアントID</span><input value={driveClientId} onChange={(event)=>onDriveClientIdChange(event.target.value)} placeholder="000000000000-xxxx.apps.googleusercontent.com" /></label><button className="drive-primary" disabled={driveBusy||!driveClientId.trim()} onClick={onDriveConnect}>{driveBusy?'接続中…':'Google Driveに接続'}</button></div> : <><label className={`auto-sync-toggle ${autoSync?'enabled':''}`}><input type="checkbox" checked={autoSync} onChange={(event)=>onAutoSyncChange(event.target.checked)}/><span><b>自動同期</b><small>マスター・仕様選択状態を変更後1.2秒で保存</small></span><em>{syncStatus}</em></label><div className="drive-actions"><button className="drive-primary" disabled={driveBusy} onClick={onDriveSave}>{driveBusy?'処理中…':'現在の全データを保存'}</button><button className="secondary" disabled={driveBusy} onClick={onDriveLoad}>Driveから全データを読み込む</button><button className="text-button" disabled={driveBusy} onClick={onDriveDisconnect}>接続を解除</button></div></>}
      <p className="drive-note">Google Cloud ConsoleでDrive APIを有効にし、承認済みJavaScript生成元へこのアプリのURLを登録してください。権限はこのアプリが作成したファイルのみに限定されます。</p>
    </section>
    <div className="csv-help"><b>CSV取込について</b><p>CSV出力で得られるヘッダーと同じ形式で作成してください。取込時は対象マスターの登録内容を全件置き換えます。確認画面に現在件数と取込後件数が表示されるため、必ず比較してから実行してください。文字コードはUTF-8、選択肢は「|」区切りです。</p></div>
  </section>;
}
function Detail({result,specs,onClose,onConfirm}:{result:UnitResult;specs:MasterData['specifications'];onClose:()=>void;onConfirm:(u:string,p:string)=>void}) { return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="drawer"><button className="close" onClick={onClose}>×</button><span className="eyebrow">UNIT {result.unit.no}</span><h2>{result.unit.name}</h2><p>{result.unit.note}</p><div className={`summary ${result.status}`}>{statusLabel[result.status]}<b>{result.candidates.length} 件</b></div><h3>PL候補と判定詳細</h3>{result.nearCandidates.length===0?<p className="empty">このユニットにはPL条件が登録されていません。</p>:result.nearCandidates.map(c=><article className={`candidate ${result.candidates.some(x=>x.id===c.id)?'eligible':''}`} key={c.id}><div><b>{c.partNumber}</b><span>{c.note||'備考なし'}</span></div>{result.status==='multiple'&&result.candidates.some(x=>x.id===c.id)&&<button onClick={()=>onConfirm(result.unit.no,c.partNumber)}>このPLを選択</button>}<table><tbody>{c.details.map(d=><tr key={d.specificationCode}><td>{d.matched?'✓':d.missing?'!':'×'}</td><td>{d.specificationCode} {specs.find(s=>s.code===d.specificationCode)?.name??''}</td><td>条件: {d.expected.map((value)=>`${value} ${optionLabel(specs,value)}`).join(' / ')}</td><td>選択: {d.actual?`${d.actual} ${optionLabel(specs,d.actual)}`:'未選択'}</td></tr>)}</tbody></table></article>)}</aside></div> }
export default App;
